name: CppCheck


on: [push, pull_request]
jobs:
  # The first job
  build:
    name: cppcheck-test
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd

    steps:           
      - name: cppcheck
        run: C:\actions-runner\_work\Notes\Notes\.github\workflows\cppcheck.bat
     
  # The second job
  upload-report:
    name: report
    needs: build
    runs-on: self-hosted
    
    steps:
    - uses: actions/upload-artifact@v2
      with:
        name: CppCheck results
        path: C:\actions-runner\_work\Notes\CppCheckReport\
