name: Open-CppCoverage

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:      
      - name: Generate coverage report
        run: |
          cd C:\actions-runner\_work
          clear.bat
          cppcoverage.bat
          
      - uses: actions/upload-artifact@v2
        with:
         name: Coverage results
         path: C:\actions-runner\_work\CoverageReport\
