name: Open-CppCoverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:      
      # - name: Generate coverage report
      #   run: |
      #     cd C:\actions-runner\_work
      #     C:\actions-runner\_work\clear.bat
      #     C:\actions-runner\_work\cppcoverage.bat

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'C:\actions-runner-Notes\_work\CoverageReport\'
          destination-github-username: 'Alina-go'
          destination-repository-name: 'Notes'
          user-email: carles3@pina.cat
          target-branch: gh-pages

      # - uses: actions/upload-artifact@v2
      #   with:
      #    name: Coverage results
      #    path: C:\actions-runner\_work\CoverageReport\
