name: Open-CppCoverage

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        
      - name: Generate coverage report
        run: |
          cd C:\Notes
          C:\Notes\clear.bat
          C:\Notes\cppcoverage.bat
          C:\Notes\Notes\GUITests\lackey_test.py
          
      - uses: actions/upload-artifact@v2
        with:
         name: Coverage results
         path: coverage_report
         
      - uses: codecov/codecov-action@v1.2.1
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # file: ./coverage.xml # optional
          flags: unittests # optional
          name: ${{ github.repository }} # optional
          fail_ci_if_error: true # optional (default = false):  
