name: Open-CppCoverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: git-bash.exe {0}

    steps:
      - name: Generate coverage report
        run: C:\actions-runner\_work\Notes\Notes\.github\workflows\cppcoverage.bat

      - name: Pushes to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: 'gh-pages'
          repository: 'Notes'

      # - uses: actions/upload-artifact@v2
      #   with:
      #    name: Coverage results
      #    path: C:\actions-runner\_work\CoverageReport\
